# def values for generate scentence:
location = str(input("a locatio that you very love this:?"))
food = str(input("that food that you very love this?:"))
person = str(input("special person you very love him?:"))
# function of generation of joke
def wizardjoke(locations, foods, persons):
    locations = location
    foods = food
    persons = person
    return print("tomorrow you go to",locations,"& when",persons,"sit on there you will are pising at dish of",foods,"ha ha ha!")
# outpot of program that has a scentence that generated by vlues
wizardjoke(location, food, person)
